-- ============================================================
-- Generic Admin: Grants
-- Replace placeholders before execution.
-- ============================================================

-- Base views
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_WAREHOUSE_COST_BY_TAG TO ROLE "<DEVELOPER_ROLE>";
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_QUERY_PERFORMANCE TO ROLE "<DEVELOPER_ROLE>";
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_USER_SPEND TO ROLE "<DEVELOPER_ROLE>";
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_SERVERLESS_COSTS TO ROLE "<DEVELOPER_ROLE>";
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_MV_REFRESH_COSTS TO ROLE "<DEVELOPER_ROLE>";
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_WAREHOUSE_EVENTS TO ROLE "<DEVELOPER_ROLE>";
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_SESSION_ACTIVITY TO ROLE "<DEVELOPER_ROLE>";
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_DATA_TRANSFER_COSTS TO ROLE "<DEVELOPER_ROLE>";
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_REPLICATION_COSTS TO ROLE "<DEVELOPER_ROLE>";
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_STORAGE_TABLE_METRICS TO ROLE "<DEVELOPER_ROLE>";
GRANT SELECT ON VIEW <APP_DB>.<APP_SCHEMA>.V_RATE_SHEET_PRICING TO ROLE "<DEVELOPER_ROLE>";

-- Semantic views
GRANT REFERENCES, SELECT ON SEMANTIC VIEW <APP_DB>.<APP_SCHEMA>.SV_WAREHOUSE_COST_ANALYSIS TO ROLE "<DEVELOPER_ROLE>";
GRANT REFERENCES, SELECT ON SEMANTIC VIEW <APP_DB>.<APP_SCHEMA>.SV_STORAGE_COST_ANALYSIS TO ROLE "<DEVELOPER_ROLE>";
GRANT REFERENCES, SELECT ON SEMANTIC VIEW <APP_DB>.<APP_SCHEMA>.SV_SERVERLESS_COSTS TO ROLE "<DEVELOPER_ROLE>";
GRANT REFERENCES, SELECT ON SEMANTIC VIEW <APP_DB>.<APP_SCHEMA>.SV_USER_SPEND TO ROLE "<DEVELOPER_ROLE>";
GRANT REFERENCES, SELECT ON SEMANTIC VIEW <APP_DB>.<APP_SCHEMA>.SV_WAREHOUSE_OPERATIONS TO ROLE "<DEVELOPER_ROLE>";
GRANT REFERENCES, SELECT ON SEMANTIC VIEW <APP_DB>.<APP_SCHEMA>.SV_SESSION_ACTIVITY TO ROLE "<DEVELOPER_ROLE>";
GRANT REFERENCES, SELECT ON SEMANTIC VIEW <APP_DB>.<APP_SCHEMA>.SV_DATA_TRANSFER_REPLICATION TO ROLE "<DEVELOPER_ROLE>";
GRANT REFERENCES, SELECT ON SEMANTIC VIEW <APP_DB>.<APP_SCHEMA>.SV_RATE_SHEET_PRICING TO ROLE "<DEVELOPER_ROLE>";

-- Agent usage
GRANT USAGE ON AGENT <APP_DB>.<APP_SCHEMA>.<AGENT_NAME> TO ROLE "<DEVELOPER_ROLE>";
